[tool.poetry]
name = "gpt-messages"
version = "0.1.0"
description = ""
authors = ["sushmitha.jagannathan <sushmitha.jagannathan@zoomrx.com>"]

[tool.poetry.dependencies]
python = "~3.7.13"
pandas = "~1.2.1"
pyChatGPT = "^0.4.2"
sentence-transformers = "~2.2.0"
streamlit = ">=1.8.1"
textblob = "~0.17.1"
xgboost = "~1.6.0"

[tool.poetry.dev-dependencies]
icecream = "^2.1.3"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
